import "./globals.css";
import React from "react";

export const metadata = {
  title: "Create Next App2",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <h1>HEADER</h1>
        {children}
        <h3>FOOTER</h3>
      </body>
    </html>
  );
}
